### ISSUE TITLE
Appsubs fail to apply CRDs: schemas are required

### ISSUE THREAD

**Issue by ahadas** [open-cluster-management/multicloud-operators-subscription#170]
We've defined an appsub that applies CRD with:
```yaml
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    operator.kubevirt.io: ""
  name: kubevirts.kubevirt.io
spec:
  additionalPrinterColumns:
  - JSONPath: .metadata.creationTimestamp
    name: Age
    type: date
  - JSONPath: .status.phase
    name: Phase
    type: string
  group: kubevirt.io
  names:
    categories:
    - all
    kind: KubeVirt
    plural: kubevirts
    shortNames:
    - kv
    - kvs
    singular: kubevirt
  scope: Namespaced
  version: v1alpha3
  versions:
  - name: v1alpha3
    served: true
    storage: true
```

It failed due to:
`E0421 17:05:01.346887       1 synchronizer.go:461] Failed to apply kind template&{map[apiVersion:apiextensions.k8s.io/v1 kind:CustomReso
urceDefinition metadata:map[annotations:map[apps.open-cluster-management.io/hosting-deployable:ec/ec-channel-CustomResourceDefinition-ku
bevirts.kubevirt.io apps.open-cluster-management.io/hosting-subscription:ec/cnv-appsub apps.open-cluster-management.io/sync-source:subgb
k8s-ec/cnv-appsub] labels:map[operator.kubevirt.io:] name:kubevirts.kubevirt.io] spec:map[additionalPrinterColumns:[map[JSONPath:.metada
ta.creationTimestamp name:Age type:date] map[JSONPath:.status.phase name:Phase type:string]] group:kubevirt.io names:map[categories:[all
] kind:KubeVirt plural:kubevirts shortNames:[kv kvs] singular:kubevirt] scope:Namespaced version:v1alpha3 versions:[map[name:v1alpha3 se
rved:true storage:true]]]]}with error:CustomResourceDefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" is invalid: spec.versions[0]
.schema.openAPIV3Schema: Required value: schemas are required`

by changing the versions to:
```yaml
versions:
  - name: v1alpha3
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cronSpec:
                type: string
              image:
                type: string
              replicas:
                type: integer
```

It works but it doesn't sound right to require this as k8s doesn't require it.

**Comment by ianzhang366** [comment]
Hi @ahadas  I believe this issue is related to the following,

https://www.openshift.com/blog/a-look-into-the-technical-details-of-kubernetes-1-16

It seems on k8s 1.16, the `apiextensions.k8s.io/v1beta1` is promoted to `apiextensions.k8s.io/v1`. At `v1`, the k8s will request the schema field, I guess when doing the conversion from the old version to the newer ones, the `schema` field is required.

Checking the k8s documentation, it seems, at the `v1beta1` example, the schema field was added to as well.

https://kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definitions/

I guess we will have to make the migration following the k8s examples since we updated our k8s client to 1.16.2,
https://github.com/open-cluster-management/multicloud-operators-subscription/blob/5240b7a3cd525a7eafc92d880ea656c88fcd0ceb/go.mod#L36

One more thing,
I noticed that the CRD, you are showing, is at `apiextensions.k8s.io/v1beta1` but the log is complaining at  `apiVersion:apiextensions.k8s.io/v1`.  

Am I missing something over here? I mean why there's version conversion, do you have any clue, or maybe this conversion is done by the k8s client?

**Comment by ahadas** [comment]
@ianzhang366  thanks for looking into this!

Unless I'm missing something, I don't see that the schema was added to the CRD of v1beta1 in the k8s documentation you pointed to:
```yaml
# Deprecated in v1.16 in favor of apiextensions.k8s.io/v1
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: crontabs.stable.example.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.example.com
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
  # either Namespaced or Cluster
  scope: Namespaced
...
```
And yeah, it seems like the version was converted by k8s (unrelated to OCM) as it happened also when I defined with kubectl:
```bash
[admin@spoke1 deploy]$ kubectl create -f /tmp/crd.yaml 
customresourcedefinition.apiextensions.k8s.io/kubevirts.kubevirt.io created
[admin@spoke1 deploy]$ kubectl get crd kubevirts.kubevirt.io -o yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2020-04-21T18:16:11Z"
  generation: 1
  labels:
    operator.kubevirt.io: ""
  name: kubevirts.kubevirt.io
  resourceVersion: "812569"
  selfLink: /apis/apiextensions.k8s.io/v1/customresourcedefinitions/kubevirts.kubevirt.io
  uid: 3519ce49-0444-405e-83d0-b85a427f2dae
spec:
  conversion:
    strategy: None
  group: kubevirt.io
  names:
    categories:
    - all
    kind: KubeVirt
    listKind: KubeVirtList
    plural: kubevirts
    shortNames:
    - kv
    - kvs
    singular: kubevirt
  preserveUnknownFields: true
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - jsonPath: .metadata.creationTimestamp
      name: Age
      type: date
    - jsonPath: .status.phase
      name: Phase
      type: string
    name: v1alpha3
    served: true
    storage: true
status:
...
```

**Comment by ianzhang366** [comment]
I was looking at the field, `validation` under the CRD spec.

The `validation` field is added on the k8s 1.16, under the validation field it has the `openAPIV3Schema`, I guess, for k8s, it leverages the `spec.validation` for the CRD version conversion. 
```
  validation:
    openAPIV3Schema:
      type: object
      properties:
        host:
          type: string
        port:
          type: string
```
https://v1-16.docs.kubernetes.io/docs/tasks/access-kubernetes-api/custom-resources/custom-resource-definition-versioning/

To our case, I believe the flow is, 
When we apply an `apiextensions.k8s.io/v1beta1` CRD via subscription, the CRD will be converted to `apiextensions.k8s.io/v1` CRD by k8s, for the conversion to happen, the k8s will checking the `spec.versions` and failed us on the missing `openAPIV3Schema`.

However, on k8s 1.16 documentation, I'm seeing the following,

```
Note: In apiextensions.k8s.io/v1beta1, there was a version field instead of versions. The version field is deprecated and optional, but if it is not empty, it must match the first item in the versions field.
```

It seems we can only use the `version` field at `apiextensions.k8s.io/v1beta1`, however, if we decide to `version` and `versions`,  the `schema` of `versions[0]` can be empty though.

```
	// +optional
	Schema *CustomResourceValidation
```

https://github.com/kubernetes/apiextensions-apiserver/blob/release-1.16/pkg/apis/apiextensions/types.go#L184-L185

Our code is basically using client-go to apply/create the `CRD`, not sure why it's somehow running the schema checking logic. It could be the case, our code is doing the version conversion before calling the apply/create.

Can you please try to moving forward via the workaround, while I'm figuring out the odd validation logic on the `schema` field?

Also, if we use ``apiextensions.k8s.io/v1`, would the problem persist in your case?
