### ISSUE TITLE
weird log for GitHub channel

### ISSUE THREAD

**Issue by ahadas** [open-cluster-management/multicloud-operators-subscription#173]
We've created the following appsub:
```yaml
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: cnv-appsub
  namespace: kubevirt
  annotations:
    apps.open-cluster-management.io/github-path: kubevirt
    apps.open-cluster-management.io/github-branch: master
spec:
  channel: ec/ec-channel
  placement:
    placementRef:
      kind: PlacementRule
      name: cnf-placement
```

That refers to the following channel of type GitHub:

```yaml
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: ec-channel
  namespace: ec
spec:
  type: GitHub
  pathname: https://github.com/danielerez/ocm-gitops-policy.git
```
And we see the following log:
`W0421 17:06:26.798052       1 helmrepo.go:373] subsciption.spec.name is missing for subscription: ec/cnv-appsub`

This looks weird as cnv-appsub has nothing to do with helm...
